# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_t.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/Work/PythonProjects/Central_Bank_Rf/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setGeometry(QtCore.QRect(0, -10, 1921, 1101))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_background.setFont(font)
        self.label_background.setStyleSheet("image: url(:/images/background_image/bg_2.png);")
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap(":/images/C:/Users/aleks/OneDrive/Рабочий стол/imgonline-com-ua-Resize-QpMTZhX9l6prh5g.png"))
        self.label_background.setObjectName("label_background")
        self.button_overview = QtWidgets.QPushButton(self.centralwidget)
        self.button_overview.setGeometry(QtCore.QRect(30, 190, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_overview.setFont(font)
        self.button_overview.setToolTipDuration(-1)
        self.button_overview.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_overview.setAutoFillBackground(False)
        self.button_overview.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/overview_light.png);\n"
"padding-right: 105;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 85;\n"
"font: bold;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/label_image/light/overview_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_overview.setIcon(icon1)
        self.button_overview.setIconSize(QtCore.QSize(20, 20))
        self.button_overview.setCheckable(False)
        self.button_overview.setAutoDefault(False)
        self.button_overview.setObjectName("button_overview")
        self.button_analytic = QtWidgets.QPushButton(self.centralwidget)
        self.button_analytic.setGeometry(QtCore.QRect(30, 260, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_analytic.setFont(font)
        self.button_analytic.setToolTipDuration(-1)
        self.button_analytic.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_analytic.setAutoFillBackground(False)
        self.button_analytic.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/analytic_light.png);\n"
"padding-right: 110;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 85;\n"
"font: bold;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/label_image/light/analytic_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(":/images/label_image/light/analytic_light.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/images/label_image/dark/analytic_dark.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_analytic.setIcon(icon2)
        self.button_analytic.setIconSize(QtCore.QSize(20, 20))
        self.button_analytic.setAutoDefault(False)
        self.button_analytic.setObjectName("button_analytic")
        self.button_product = QtWidgets.QPushButton(self.centralwidget)
        self.button_product.setGeometry(QtCore.QRect(30, 330, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_product.setFont(font)
        self.button_product.setToolTipDuration(-1)
        self.button_product.setAutoFillBackground(False)
        self.button_product.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/product_light.png);\n"
"padding-right: 115;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 85;\n"
"font: bold;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/label_image/light/product_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_product.setIcon(icon3)
        self.button_product.setIconSize(QtCore.QSize(20, 20))
        self.button_product.setAutoDefault(False)
        self.button_product.setObjectName("button_product")
        self.button_order = QtWidgets.QPushButton(self.centralwidget)
        self.button_order.setGeometry(QtCore.QRect(30, 400, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_order.setFont(font)
        self.button_order.setToolTipDuration(-1)
        self.button_order.setAutoFillBackground(False)
        self.button_order.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/order_light.png);\n"
"padding-right: 135;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 105;\n"
"font: bold;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/label_image/light/order_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_order.setIcon(icon4)
        self.button_order.setIconSize(QtCore.QSize(20, 20))
        self.button_order.setAutoDefault(False)
        self.button_order.setObjectName("button_order")
        self.button_transaction = QtWidgets.QPushButton(self.centralwidget)
        self.button_transaction.setGeometry(QtCore.QRect(30, 470, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_transaction.setFont(font)
        self.button_transaction.setToolTipDuration(-1)
        self.button_transaction.setAutoFillBackground(False)
        self.button_transaction.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/overview_light.png);\n"
"padding-right: 78;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 38;\n"
"font: bold;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/label_image/light/transaction_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_transaction.setIcon(icon5)
        self.button_transaction.setIconSize(QtCore.QSize(20, 20))
        self.button_transaction.setAutoDefault(False)
        self.button_transaction.setObjectName("button_transaction")
        self.button_report = QtWidgets.QPushButton(self.centralwidget)
        self.button_report.setGeometry(QtCore.QRect(30, 540, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_report.setFont(font)
        self.button_report.setToolTipDuration(-1)
        self.button_report.setAutoFillBackground(False)
        self.button_report.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/overview_light.png);\n"
"padding-right: 133;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 90;\n"
"font: bold;\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/label_image/light/report_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_report.setIcon(icon6)
        self.button_report.setIconSize(QtCore.QSize(20, 20))
        self.button_report.setAutoDefault(False)
        self.button_report.setObjectName("button_report")
        self.label_menu = QtWidgets.QLabel(self.centralwidget)
        self.label_menu.setGeometry(QtCore.QRect(20, 160, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.label_menu.setFont(font)
        self.label_menu.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_menu.setObjectName("label_menu")
        self.label_rectangle = QtWidgets.QLabel(self.centralwidget)
        self.label_rectangle.setGeometry(QtCore.QRect(0, 682, 274, 201))
        self.label_rectangle.setStyleSheet("background-color: rgb(17, 18, 25);")
        self.label_rectangle.setText("")
        self.label_rectangle.setObjectName("label_rectangle")
        self.label_others = QtWidgets.QLabel(self.centralwidget)
        self.label_others.setGeometry(QtCore.QRect(20, 650, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.label_others.setFont(font)
        self.label_others.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_others.setObjectName("label_others")
        self.button_setting = QtWidgets.QPushButton(self.centralwidget)
        self.button_setting.setGeometry(QtCore.QRect(30, 690, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_setting.setFont(font)
        self.button_setting.setToolTipDuration(-1)
        self.button_setting.setAutoFillBackground(False)
        self.button_setting.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/setting_light.png);\n"
"padding-right: 133;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 90;\n"
"font: bold;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/label_image/light/setting_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_setting.setIcon(icon7)
        self.button_setting.setIconSize(QtCore.QSize(20, 20))
        self.button_setting.setAutoDefault(False)
        self.button_setting.setObjectName("button_setting")
        self.button_message = QtWidgets.QPushButton(self.centralwidget)
        self.button_message.setGeometry(QtCore.QRect(30, 760, 231, 55))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_message.setFont(font)
        self.button_message.setToolTipDuration(-1)
        self.button_message.setAutoFillBackground(False)
        self.button_message.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/message_light.png);\n"
"padding-right: 125;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 90;\n"
"font: bold;\n"
"}\n"
"\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/label_image/light/message_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_message.setIcon(icon8)
        self.button_message.setIconSize(QtCore.QSize(20, 20))
        self.button_message.setAutoDefault(False)
        self.button_message.setObjectName("button_message")
        self.button_help = QtWidgets.QPushButton(self.centralwidget)
        self.button_help.setGeometry(QtCore.QRect(30, 834, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_help.setFont(font)
        self.button_help.setToolTipDuration(-1)
        self.button_help.setAutoFillBackground(False)
        self.button_help.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"qproperty-icon: url(:/images/label_image/light/help_light.png);\n"
"padding-right: 84;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"padding-right: 44;\n"
"font: bold;\n"
"}\n"
"\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/label_image/light/help_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_help.setIcon(icon9)
        self.button_help.setIconSize(QtCore.QSize(20, 20))
        self.button_help.setAutoDefault(False)
        self.button_help.setObjectName("button_help")
        self.label_background_profile = QtWidgets.QLabel(self.centralwidget)
        self.label_background_profile.setGeometry(QtCore.QRect(30, 920, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_background_profile.setFont(font)
        self.label_background_profile.setStyleSheet("background-color: rgb(41, 41, 44);\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 10px;\n"
"padding-left: 66;\n"
"padding-top: 20;")
        self.label_background_profile.setObjectName("label_background_profile")
        self.label_image_avatar = QtWidgets.QLabel(self.centralwidget)
        self.label_image_avatar.setGeometry(QtCore.QRect(40, 930, 49, 49))
        self.label_image_avatar.setStyleSheet("image: url(:/images/help_image/avatar.png);")
        self.label_image_avatar.setText("")
        self.label_image_avatar.setObjectName("label_image_avatar")
        self.label_name_avatar = QtWidgets.QLabel(self.centralwidget)
        self.label_name_avatar.setGeometry(QtCore.QRect(100, 930, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.label_name_avatar.setFont(font)
        self.label_name_avatar.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name_avatar.setObjectName("label_name_avatar")
        self.label_help_background = QtWidgets.QLabel(self.centralwidget)
        self.label_help_background.setGeometry(QtCore.QRect(1099, -3, 821, 211))
        self.label_help_background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 201, 255, 255), stop:0.994318 rgba(0, 0, 0, 255));")
        self.label_help_background.setText("")
        self.label_help_background.setObjectName("label_help_background")
        self.label_help_background_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_help_background_2.setGeometry(QtCore.QRect(275, 0, 831, 208))
        self.label_help_background_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));")
        self.label_help_background_2.setText("")
        self.label_help_background_2.setObjectName("label_help_background_2")
        self.label_name_page = QtWidgets.QLabel(self.centralwidget)
        self.label_name_page.setGeometry(QtCore.QRect(300, 40, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_name_page.setFont(font)
        self.label_name_page.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name_page.setObjectName("label_name_page")
        self.button_notification_check = QtWidgets.QPushButton(self.centralwidget)
        self.button_notification_check.setGeometry(QtCore.QRect(1840, 40, 60, 60))
        self.button_notification_check.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(10, 34, 39, 255), stop:1 rgba(0, 0, 0, 255));\n"
"border: 0;\n"
"border-radius: 10;")
        self.button_notification_check.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/help_image/notification.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_notification_check.setIcon(icon10)
        self.button_notification_check.setIconSize(QtCore.QSize(20, 20))
        self.button_notification_check.setObjectName("button_notification_check")
        self.label_notification_checker = QtWidgets.QLabel(self.centralwidget)
        self.label_notification_checker.setGeometry(QtCore.QRect(1870, 60, 10, 10))
        self.label_notification_checker.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border: 10;\n"
"border-radius: 5;")
        self.label_notification_checker.setText("")
        self.label_notification_checker.setObjectName("label_notification_checker")
        self.textbox_search = QtWidgets.QLineEdit(self.centralwidget)
        self.textbox_search.setGeometry(QtCore.QRect(1400, 46, 434, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.textbox_search.setFont(font)
        self.textbox_search.setStyleSheet("border: 0;\n"
"color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(0, 64, 81, 255));\n"
"border-radius:11.6;\n"
"padding-left: 10;\n"
"")
        self.textbox_search.setObjectName("textbox_search")
        self.button_search = QtWidgets.QPushButton(self.centralwidget)
        self.button_search.setGeometry(QtCore.QRect(1356, 46, 54, 51))
        self.button_search.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-top-left-radius: 11.6;\n"
"border-bottom-left-radius: 11.6;")
        self.button_search.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/help_image/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_search.setIcon(icon11)
        self.button_search.setIconSize(QtCore.QSize(20, 20))
        self.button_search.setObjectName("button_search")
        self.label_currence_header = QtWidgets.QLabel(self.centralwidget)
        self.label_currence_header.setGeometry(QtCore.QRect(300, 240, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_currence_header.setFont(font)
        self.label_currence_header.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_currence_header.setObjectName("label_currence_header")
        self.label_value_one = QtWidgets.QLabel(self.centralwidget)
        self.label_value_one.setGeometry(QtCore.QRect(300, 480, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_value_one.setFont(font)
        self.label_value_one.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_value_one.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_one.setObjectName("label_value_one")
        self.label_value_three = QtWidgets.QLabel(self.centralwidget)
        self.label_value_three.setGeometry(QtCore.QRect(300, 410, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_value_three.setFont(font)
        self.label_value_three.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_value_three.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_three.setObjectName("label_value_three")
        self.label_value_two = QtWidgets.QLabel(self.centralwidget)
        self.label_value_two.setGeometry(QtCore.QRect(300, 445, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_value_two.setFont(font)
        self.label_value_two.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_value_two.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_two.setObjectName("label_value_two")
        self.label_value_four = QtWidgets.QLabel(self.centralwidget)
        self.label_value_four.setGeometry(QtCore.QRect(300, 378, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_value_four.setFont(font)
        self.label_value_four.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_value_four.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_four.setObjectName("label_value_four")
        self.label_value_five = QtWidgets.QLabel(self.centralwidget)
        self.label_value_five.setGeometry(QtCore.QRect(300, 345, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_value_five.setFont(font)
        self.label_value_five.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_value_five.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_five.setObjectName("label_value_five")
        self.label_value_six = QtWidgets.QLabel(self.centralwidget)
        self.label_value_six.setGeometry(QtCore.QRect(300, 310, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_value_six.setFont(font)
        self.label_value_six.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_value_six.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_six.setObjectName("label_value_six")
        self.label_month = QtWidgets.QLabel(self.centralwidget)
        self.label_month.setGeometry(QtCore.QRect(360, 500, 20, 17))
        self.label_month.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month.setObjectName("label_month")
        self.label_month_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_2.setGeometry(QtCore.QRect(410, 500, 20, 17))
        self.label_month_2.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_2.setObjectName("label_month_2")
        self.label_month_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_3.setGeometry(QtCore.QRect(460, 500, 20, 17))
        self.label_month_3.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_3.setObjectName("label_month_3")
        self.label_month_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_4.setGeometry(QtCore.QRect(510, 500, 20, 17))
        self.label_month_4.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_4.setObjectName("label_month_4")
        self.label_month_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_5.setGeometry(QtCore.QRect(560, 500, 20, 17))
        self.label_month_5.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_5.setObjectName("label_month_5")
        self.label_month_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_6.setGeometry(QtCore.QRect(610, 500, 20, 17))
        self.label_month_6.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_6.setObjectName("label_month_6")
        self.label_month_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_7.setGeometry(QtCore.QRect(660, 500, 20, 17))
        self.label_month_7.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_7.setObjectName("label_month_7")
        self.label_month_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_8.setGeometry(QtCore.QRect(710, 500, 20, 17))
        self.label_month_8.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_8.setObjectName("label_month_8")
        self.label_month_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_9.setGeometry(QtCore.QRect(760, 500, 20, 17))
        self.label_month_9.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_9.setObjectName("label_month_9")
        self.label_month_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_10.setGeometry(QtCore.QRect(810, 500, 20, 17))
        self.label_month_10.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_10.setObjectName("label_month_10")
        self.label_month_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_11.setGeometry(QtCore.QRect(860, 500, 20, 17))
        self.label_month_11.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_11.setObjectName("label_month_11")
        self.label_month_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_month_12.setGeometry(QtCore.QRect(910, 500, 20, 17))
        self.label_month_12.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_month_12.setObjectName("label_month_12")
        self.combobox_early = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_early.setGeometry(QtCore.QRect(860, 250, 80, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.combobox_early.setFont(font)
        self.combobox_early.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.combobox_early.setAcceptDrops(False)
        self.combobox_early.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combobox_early.setStyleSheet("QComboBox{\n"
"background-color: rgb(41, 41, 44);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5;\n"
"border-color: rgb(41, 41, 44);\n"
"padding-left: 15;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"image: url(:/images/help_image/arrow_combo_box.png);\n"
"width: 10;\n"
"height:10;\n"
"margin-top: 5;\n"
"margin-right:5;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 4 solid;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"font-size: 8;\n"
"padding: 5;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"outline: 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.combobox_early.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combobox_early.setObjectName("combobox_early")
        self.combobox_early.addItem("")
        self.combobox_early.addItem("")
        self.combobox_early.addItem("")
        self.combobox_early.addItem("")
        self.combobox_early.addItem("")
        self.combobox_monthly = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_monthly.setGeometry(QtCore.QRect(755, 250, 95, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.combobox_monthly.setFont(font)
        self.combobox_monthly.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.combobox_monthly.setAcceptDrops(False)
        self.combobox_monthly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combobox_monthly.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5;\n"
"border-color: rgb(41, 41, 44);\n"
"padding-left: 15;\n"
"}\n"
"QComboBox:hover{\n"
"background-color: rgb(41, 41, 44);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"image: url(:/images/help_image/arrow_combo_box.png);\n"
"width: 10;\n"
"height:10;\n"
"margin-top: 5;\n"
"margin-right:5;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 4 solid;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"font-size: 8;\n"
"padding: 5;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"outline: 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.combobox_monthly.setMaxVisibleItems(10)
        self.combobox_monthly.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combobox_monthly.setObjectName("combobox_monthly")
        self.combobox_monthly.addItem("")
        self.combobox_monthly.addItem("")
        self.combobox_monthly.addItem("")
        self.combobox_monthly.addItem("")
        self.combobox_monthly.addItem("")
        self.combobox_weekly = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_weekly.setGeometry(QtCore.QRect(660, 250, 91, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.combobox_weekly.setFont(font)
        self.combobox_weekly.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.combobox_weekly.setAcceptDrops(False)
        self.combobox_weekly.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combobox_weekly.setStyleSheet("QComboBox{\n"
"background-color: rgb(255, 0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5;\n"
"border-color: rgb(41, 41, 44);\n"
"padding-left: 15;\n"
"}\n"
"QComboBox:hover{\n"
"background-color: rgb(41, 41, 44);\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"image: url(:/images/help_image/arrow_combo_box.png);\n"
"width: 10;\n"
"height:10;\n"
"margin-top: 5;\n"
"margin-right:5;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 4 solid;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"font-size: 8;\n"
"padding: 5;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"outline: 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.combobox_weekly.setMaxVisibleItems(10)
        self.combobox_weekly.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combobox_weekly.setObjectName("combobox_weekly")
        self.combobox_weekly.addItem("")
        self.combobox_weekly.addItem("")
        self.combobox_weekly.addItem("")
        self.combobox_weekly.addItem("")
        self.combobox_weekly.addItem("")
        self.label_percent_value = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_value.setGeometry(QtCore.QRect(288, 796, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_percent_value.setFont(font)
        self.label_percent_value.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_percent_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_value.setObjectName("label_percent_value")
        self.label_percent_value_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_value_2.setGeometry(QtCore.QRect(290, 764, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_percent_value_2.setFont(font)
        self.label_percent_value_2.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_percent_value_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_value_2.setObjectName("label_percent_value_2")
        self.label_percent_value_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_value_3.setGeometry(QtCore.QRect(290, 730, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_percent_value_3.setFont(font)
        self.label_percent_value_3.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_percent_value_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_value_3.setObjectName("label_percent_value_3")
        self.label_percent_value_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_value_4.setGeometry(QtCore.QRect(290, 696, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_percent_value_4.setFont(font)
        self.label_percent_value_4.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_percent_value_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_value_4.setObjectName("label_percent_value_4")
        self.label_percent_value_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_value_5.setGeometry(QtCore.QRect(290, 662, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_percent_value_5.setFont(font)
        self.label_percent_value_5.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_percent_value_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_value_5.setObjectName("label_percent_value_5")
        self.label_percent_value_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_percent_value_6.setGeometry(QtCore.QRect(290, 628, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_percent_value_6.setFont(font)
        self.label_percent_value_6.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_percent_value_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_percent_value_6.setObjectName("label_percent_value_6")
        self.label_grow_month = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month.setGeometry(QtCore.QRect(347, 817, 20, 17))
        self.label_grow_month.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month.setObjectName("label_grow_month")
        self.label_grow_header = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_header.setGeometry(QtCore.QRect(300, 560, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_grow_header.setFont(font)
        self.label_grow_header.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_grow_header.setObjectName("label_grow_header")
        self.label_grow_month_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_2.setGeometry(QtCore.QRect(397, 817, 20, 17))
        self.label_grow_month_2.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_2.setObjectName("label_grow_month_2")
        self.label_grow_month_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_3.setGeometry(QtCore.QRect(446, 817, 20, 17))
        self.label_grow_month_3.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_3.setObjectName("label_grow_month_3")
        self.label_grow_month_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_4.setGeometry(QtCore.QRect(494, 817, 20, 17))
        self.label_grow_month_4.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_4.setObjectName("label_grow_month_4")
        self.label_grow_month_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_5.setGeometry(QtCore.QRect(543, 817, 20, 17))
        self.label_grow_month_5.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_5.setObjectName("label_grow_month_5")
        self.label_grow_month_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_6.setGeometry(QtCore.QRect(592, 817, 20, 17))
        self.label_grow_month_6.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_6.setObjectName("label_grow_month_6")
        self.label_grow_month_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_7.setGeometry(QtCore.QRect(632, 817, 20, 17))
        self.label_grow_month_7.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_7.setObjectName("label_grow_month_7")
        self.label_grow_month_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_8.setGeometry(QtCore.QRect(680, 817, 20, 17))
        self.label_grow_month_8.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_8.setObjectName("label_grow_month_8")
        self.label_grow_month_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_9.setGeometry(QtCore.QRect(728, 817, 20, 17))
        self.label_grow_month_9.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_9.setObjectName("label_grow_month_9")
        self.label_grow_month_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_10.setGeometry(QtCore.QRect(778, 817, 20, 17))
        self.label_grow_month_10.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_10.setObjectName("label_grow_month_10")
        self.label_grow_month_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_11.setGeometry(QtCore.QRect(827, 817, 20, 17))
        self.label_grow_month_11.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_11.setObjectName("label_grow_month_11")
        self.label_grow_month_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_grow_month_12.setGeometry(QtCore.QRect(876, 817, 20, 17))
        self.label_grow_month_12.setStyleSheet("color: rgb(137, 137, 137);")
        self.label_grow_month_12.setObjectName("label_grow_month_12")
        self.combobox_early_2 = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_early_2.setGeometry(QtCore.QRect(780, 560, 131, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.combobox_early_2.setFont(font)
        self.combobox_early_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.combobox_early_2.setAcceptDrops(False)
        self.combobox_early_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combobox_early_2.setStyleSheet("QComboBox{\n"
"background-color: rgb(41, 41, 44);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5;\n"
"border-color: rgb(41, 41, 44);\n"
"padding-left: 15;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"image: url(:/images/help_image/arrow_combo_box.png);\n"
"width: 10;\n"
"height:10;\n"
"margin-top: 5;\n"
"margin-right:5;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 4 solid;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"font-size: 8;\n"
"padding: 5;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"outline: 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.combobox_early_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combobox_early_2.setObjectName("combobox_early_2")
        self.combobox_early_2.addItem("")
        self.combobox_early_2.addItem("")
        self.combobox_early_2.addItem("")
        self.combobox_early_2.addItem("")
        self.combobox_early_2.addItem("")
        self.label_best_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_best_percent.setGeometry(QtCore.QRect(328, 978, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.label_best_percent.setFont(font)
        self.label_best_percent.setStyleSheet("color: rgb(107, 235, 164);")
        self.label_best_percent.setObjectName("label_best_percent")
        self.label_value_is_best = QtWidgets.QLabel(self.centralwidget)
        self.label_value_is_best.setGeometry(QtCore.QRect(310, 940, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_is_best.setFont(font)
        self.label_value_is_best.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_is_best.setObjectName("label_value_is_best")
        self.label_best_value = QtWidgets.QLabel(self.centralwidget)
        self.label_best_value.setGeometry(QtCore.QRect(310, 900, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_best_value.setFont(font)
        self.label_best_value.setStyleSheet("color: rgb(209, 209, 209);")
        self.label_best_value.setObjectName("label_best_value")
        self.label_best_from = QtWidgets.QLabel(self.centralwidget)
        self.label_best_from.setGeometry(QtCore.QRect(374, 978, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_best_from.setFont(font)
        self.label_best_from.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_best_from.setObjectName("label_best_from")
        self.label_worst_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_worst_percent.setGeometry(QtCore.QRect(677, 978, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.label_worst_percent.setFont(font)
        self.label_worst_percent.setStyleSheet("color: rgb(245, 37, 37);")
        self.label_worst_percent.setObjectName("label_worst_percent")
        self.label_worst_value = QtWidgets.QLabel(self.centralwidget)
        self.label_worst_value.setGeometry(QtCore.QRect(655, 900, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_worst_value.setFont(font)
        self.label_worst_value.setStyleSheet("color: rgb(209, 209, 209);")
        self.label_worst_value.setObjectName("label_worst_value")
        self.label_worst_from = QtWidgets.QLabel(self.centralwidget)
        self.label_worst_from.setGeometry(QtCore.QRect(729, 978, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_worst_from.setFont(font)
        self.label_worst_from.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_worst_from.setObjectName("label_worst_from")
        self.label_value_is_worst = QtWidgets.QLabel(self.centralwidget)
        self.label_value_is_worst.setGeometry(QtCore.QRect(655, 940, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_is_worst.setFont(font)
        self.label_value_is_worst.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_is_worst.setObjectName("label_value_is_worst")
        self.label_average_from = QtWidgets.QLabel(self.centralwidget)
        self.label_average_from.setGeometry(QtCore.QRect(1084, 978, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.label_average_from.setFont(font)
        self.label_average_from.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_average_from.setObjectName("label_average_from")
        self.label_value_is_average = QtWidgets.QLabel(self.centralwidget)
        self.label_value_is_average.setGeometry(QtCore.QRect(1010, 940, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_value_is_average.setFont(font)
        self.label_value_is_average.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_is_average.setObjectName("label_value_is_average")
        self.label_average_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_average_percent.setGeometry(QtCore.QRect(1030, 980, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.label_average_percent.setFont(font)
        self.label_average_percent.setStyleSheet("color: rgb(107, 235, 164);")
        self.label_average_percent.setObjectName("label_average_percent")
        self.label_average_value = QtWidgets.QLabel(self.centralwidget)
        self.label_average_value.setGeometry(QtCore.QRect(1010, 900, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_average_value.setFont(font)
        self.label_average_value.setStyleSheet("color: rgb(209, 209, 209);")
        self.label_average_value.setObjectName("label_average_value")
        self.label_help_average = QtWidgets.QLabel(self.centralwidget)
        self.label_help_average.setGeometry(QtCore.QRect(995, 973, 91, 31))
        self.label_help_average.setStyleSheet("image: url(:/images/help_image/best.png);")
        self.label_help_average.setText("")
        self.label_help_average.setObjectName("label_help_average")
        self.label_Requested_data = QtWidgets.QLabel(self.centralwidget)
        self.label_Requested_data.setGeometry(QtCore.QRect(990, 230, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(16)
        self.label_Requested_data.setFont(font)
        self.label_Requested_data.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Requested_data.setObjectName("label_Requested_data")
        self.label_helper_percent = QtWidgets.QLabel(self.centralwidget)
        self.label_helper_percent.setGeometry(QtCore.QRect(615, 640, 50, 40))
        self.label_helper_percent.setStyleSheet("image: url(:/images/help_image/helper.png);")
        self.label_helper_percent.setText("")
        self.label_helper_percent.setObjectName("label_helper_percent")
        self.label_helper_percent_value = QtWidgets.QLabel(self.centralwidget)
        self.label_helper_percent_value.setGeometry(QtCore.QRect(629, 648, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(9)
        self.label_helper_percent_value.setFont(font)
        self.label_helper_percent_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_helper_percent_value.setObjectName("label_helper_percent_value")
        self.label_numcode = QtWidgets.QLabel(self.centralwidget)
        self.label_numcode.setGeometry(QtCore.QRect(980, 310, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_numcode.setFont(font)
        self.label_numcode.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_numcode.setObjectName("label_numcode")
        self.label_charcode = QtWidgets.QLabel(self.centralwidget)
        self.label_charcode.setGeometry(QtCore.QRect(1080, 310, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_charcode.setFont(font)
        self.label_charcode.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_charcode.setObjectName("label_charcode")
        self.label_nominal = QtWidgets.QLabel(self.centralwidget)
        self.label_nominal.setGeometry(QtCore.QRect(1180, 310, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_nominal.setFont(font)
        self.label_nominal.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nominal.setObjectName("label_nominal")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(1320, 310, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_name.setObjectName("label_name")
        self.label_value = QtWidgets.QLabel(self.centralwidget)
        self.label_value.setGeometry(QtCore.QRect(1530, 310, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value.setFont(font)
        self.label_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value.setObjectName("label_value")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(1650, 310, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_date.setObjectName("label_date")
        self.label_value_numcode_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_numcode_1.setGeometry(QtCore.QRect(990, 355, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.label_value_numcode_1.setFont(font)
        self.label_value_numcode_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_numcode_1.setObjectName("label_value_numcode_1")
        self.label_value_charcode_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_charcode_1.setGeometry(QtCore.QRect(1090, 355, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.label_value_charcode_1.setFont(font)
        self.label_value_charcode_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_charcode_1.setObjectName("label_value_charcode_1")
        self.label_value_nominal_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_nominal_1.setGeometry(QtCore.QRect(1180, 355, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.label_value_nominal_1.setFont(font)
        self.label_value_nominal_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_nominal_1.setObjectName("label_value_nominal_1")
        self.label_value_date_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_date_1.setGeometry(QtCore.QRect(1640, 355, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.label_value_date_1.setFont(font)
        self.label_value_date_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_date_1.setObjectName("label_value_date_1")
        self.label_value_name_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_name_1.setGeometry(QtCore.QRect(1260, 350, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.label_value_name_1.setFont(font)
        self.label_value_name_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_name_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_name_1.setObjectName("label_value_name_1")
        self.label_value_value_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_value_1.setGeometry(QtCore.QRect(1530, 355, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(11)
        self.label_value_value_1.setFont(font)
        self.label_value_value_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_value_1.setObjectName("label_value_value_1")
        self.button_filter_data = QtWidgets.QPushButton(self.centralwidget)
        self.button_filter_data.setGeometry(QtCore.QRect(1760, 560, 120, 35))
        self.button_filter_data.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.button_filter_data.setFont(font)
        self.button_filter_data.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_filter_data.setStyleSheet("background-color: rgb(41, 41, 44);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5;\n"
"border-color: rgb(41, 41, 44);\n"
"padding-right: 25;\n"
"\n"
"QPushButton QIcon{\n"
"color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/help_image/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon12.addPixmap(QtGui.QPixmap(":/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/help_image/filter_light.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon12.addPixmap(QtGui.QPixmap(":/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/help_image/filter_black.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.button_filter_data.setIcon(icon12)
        self.button_filter_data.setShortcut("")
        self.button_filter_data.setAutoRepeatInterval(100)
        self.button_filter_data.setObjectName("button_filter_data")
        self.button_set_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_set_1.setGeometry(QtCore.QRect(1790, 350, 75, 23))
        self.button_set_1.setStyleSheet("border: 0;")
        self.button_set_1.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/label_image/light/set_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_set_1.setIcon(icon13)
        self.button_set_1.setIconSize(QtCore.QSize(20, 20))
        self.button_set_1.setObjectName("button_set_1")
        self.label_value_charcode_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_charcode_2.setGeometry(QtCore.QRect(1090, 395, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_charcode_2.setFont(font)
        self.label_value_charcode_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_charcode_2.setObjectName("label_value_charcode_2")
        self.label_value_date_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_date_2.setGeometry(QtCore.QRect(1640, 395, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_date_2.setFont(font)
        self.label_value_date_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_date_2.setObjectName("label_value_date_2")
        self.label_value_nominal_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_nominal_2.setGeometry(QtCore.QRect(1180, 395, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_nominal_2.setFont(font)
        self.label_value_nominal_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_nominal_2.setObjectName("label_value_nominal_2")
        self.label_value_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_name_2.setGeometry(QtCore.QRect(1260, 390, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_name_2.setFont(font)
        self.label_value_name_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_name_2.setObjectName("label_value_name_2")
        self.label_value_numcode_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_numcode_2.setGeometry(QtCore.QRect(990, 395, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_numcode_2.setFont(font)
        self.label_value_numcode_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_numcode_2.setObjectName("label_value_numcode_2")
        self.label_value_value_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_value_2.setGeometry(QtCore.QRect(1530, 395, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_value_2.setFont(font)
        self.label_value_value_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_value_2.setObjectName("label_value_value_2")
        self.label_value_charcode_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_charcode_3.setGeometry(QtCore.QRect(1090, 435, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_charcode_3.setFont(font)
        self.label_value_charcode_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_charcode_3.setObjectName("label_value_charcode_3")
        self.label_value_date_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_date_3.setGeometry(QtCore.QRect(1640, 435, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_date_3.setFont(font)
        self.label_value_date_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_date_3.setObjectName("label_value_date_3")
        self.label_value_nominal_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_nominal_3.setGeometry(QtCore.QRect(1180, 435, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_nominal_3.setFont(font)
        self.label_value_nominal_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_nominal_3.setObjectName("label_value_nominal_3")
        self.label_value_name_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_name_3.setGeometry(QtCore.QRect(1260, 430, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_name_3.setFont(font)
        self.label_value_name_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_name_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_name_3.setObjectName("label_value_name_3")
        self.label_value_numcode_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_numcode_3.setGeometry(QtCore.QRect(990, 435, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_numcode_3.setFont(font)
        self.label_value_numcode_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_numcode_3.setObjectName("label_value_numcode_3")
        self.label_value_value_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_value_3.setGeometry(QtCore.QRect(1530, 435, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_value_3.setFont(font)
        self.label_value_value_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_value_3.setObjectName("label_value_value_3")
        self.label_value_charcode_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_charcode_4.setGeometry(QtCore.QRect(1090, 475, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_charcode_4.setFont(font)
        self.label_value_charcode_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_charcode_4.setObjectName("label_value_charcode_4")
        self.label_value_date_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_date_4.setGeometry(QtCore.QRect(1640, 475, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_date_4.setFont(font)
        self.label_value_date_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_date_4.setObjectName("label_value_date_4")
        self.label_value_nominal_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_nominal_4.setGeometry(QtCore.QRect(1180, 475, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_nominal_4.setFont(font)
        self.label_value_nominal_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_nominal_4.setObjectName("label_value_nominal_4")
        self.label_value_name_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_name_4.setGeometry(QtCore.QRect(1260, 470, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_name_4.setFont(font)
        self.label_value_name_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_name_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_name_4.setObjectName("label_value_name_4")
        self.label_value_numcode_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_numcode_4.setGeometry(QtCore.QRect(990, 475, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_numcode_4.setFont(font)
        self.label_value_numcode_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_numcode_4.setObjectName("label_value_numcode_4")
        self.label_value_value_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_value_4.setGeometry(QtCore.QRect(1530, 475, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_value_4.setFont(font)
        self.label_value_value_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_value_4.setObjectName("label_value_value_4")
        self.label_value_charcode_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_charcode_5.setGeometry(QtCore.QRect(1090, 515, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_charcode_5.setFont(font)
        self.label_value_charcode_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_charcode_5.setObjectName("label_value_charcode_5")
        self.label_value_date_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_date_5.setGeometry(QtCore.QRect(1640, 515, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_date_5.setFont(font)
        self.label_value_date_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_date_5.setObjectName("label_value_date_5")
        self.label_value_nominal_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_nominal_5.setGeometry(QtCore.QRect(1180, 515, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_nominal_5.setFont(font)
        self.label_value_nominal_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_nominal_5.setObjectName("label_value_nominal_5")
        self.label_value_name_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_name_5.setGeometry(QtCore.QRect(1260, 510, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_name_5.setFont(font)
        self.label_value_name_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_name_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_name_5.setObjectName("label_value_name_5")
        self.label_value_numcode_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_numcode_5.setGeometry(QtCore.QRect(990, 515, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_numcode_5.setFont(font)
        self.label_value_numcode_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_numcode_5.setObjectName("label_value_numcode_5")
        self.label_value_value_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_value_value_5.setGeometry(QtCore.QRect(1530, 515, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(12)
        self.label_value_value_5.setFont(font)
        self.label_value_value_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_value_value_5.setObjectName("label_value_value_5")
        self.button_back_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_back_pag.setGeometry(QtCore.QRect(1290, 250, 75, 23))
        self.button_back_pag.setStyleSheet("image: url(:/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/help_image/vector_left_active.png);\n"
"background-color: rgb(255, 0, 0, 0);")
        self.button_back_pag.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/help_image/vector_left_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_back_pag.setIcon(icon14)
        self.button_back_pag.setObjectName("button_back_pag")
        self.button_next_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_next_pag.setGeometry(QtCore.QRect(1460, 250, 75, 23))
        self.button_next_pag.setStyleSheet("background-color: rgb(255, 0, 0, 0);\n"
"image: url(:/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/help_image/vector_right_active.png);")
        self.button_next_pag.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/help_image/vector_right_active.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_next_pag.setIcon(icon15)
        self.button_next_pag.setObjectName("button_next_pag")
        self.button_set_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_set_2.setGeometry(QtCore.QRect(1790, 390, 75, 23))
        self.button_set_2.setStyleSheet("border: 0;\n"
"image: url(:/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/label_image/light/set_light.png);")
        self.button_set_2.setText("")
        self.button_set_2.setIcon(icon13)
        self.button_set_2.setIconSize(QtCore.QSize(20, 20))
        self.button_set_2.setObjectName("button_set_2")
        self.button_set_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_set_3.setGeometry(QtCore.QRect(1790, 430, 75, 23))
        self.button_set_3.setStyleSheet("border: 0;\n"
"image: url(:/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/label_image/light/set_light.png);")
        self.button_set_3.setText("")
        self.button_set_3.setIcon(icon13)
        self.button_set_3.setIconSize(QtCore.QSize(20, 20))
        self.button_set_3.setObjectName("button_set_3")
        self.button_set_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_set_4.setGeometry(QtCore.QRect(1790, 470, 75, 23))
        self.button_set_4.setStyleSheet("border: 0;\n"
"image: url(:/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/label_image/light/set_light.png);")
        self.button_set_4.setText("")
        self.button_set_4.setIcon(icon13)
        self.button_set_4.setIconSize(QtCore.QSize(20, 20))
        self.button_set_4.setObjectName("button_set_4")
        self.button_set_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_set_5.setGeometry(QtCore.QRect(1790, 510, 75, 23))
        self.button_set_5.setStyleSheet("border: 0;\n"
"image: url(:/images/C:/Users/aleks/OneDrive/Рабочий стол/resources/label_image/light/set_light.png);")
        self.button_set_5.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/images/label_image/light/set_light.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_set_5.setIcon(icon16)
        self.button_set_5.setIconSize(QtCore.QSize(20, 20))
        self.button_set_5.setObjectName("button_set_5")
        self.combobox_sort_data = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_sort_data.setGeometry(QtCore.QRect(1729, 240, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        font.setPointSize(10)
        self.combobox_sort_data.setFont(font)
        self.combobox_sort_data.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.combobox_sort_data.setAcceptDrops(False)
        self.combobox_sort_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combobox_sort_data.setStyleSheet("QComboBox{\n"
"background-color: rgb(41, 41, 44);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5;\n"
"border-color: rgb(41, 41, 44);\n"
"padding-left: 15;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow{\n"
"image: url(:/images/help_image/arrow_combo_box.png);\n"
"width: 10;\n"
"height:10;\n"
"margin-top: 5;\n"
"margin-right:5;\n"
"}\n"
"\n"
"QComboBox:on{\n"
"border: 4 solid;\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"font-size: 8;\n"
"padding: 5;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"outline: 0;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.combobox_sort_data.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.combobox_sort_data.setObjectName("combobox_sort_data")
        self.combobox_sort_data.addItem("")
        self.combobox_sort_data.addItem("")
        self.combobox_sort_data.addItem("")
        self.combobox_sort_data.addItem("")
        self.combobox_sort_data.addItem("")
        self.combobox_sort_data.addItem("")
        self.button_arrow_up = QtWidgets.QPushButton(self.centralwidget)
        self.button_arrow_up.setGeometry(QtCore.QRect(1690, 243, 51, 31))
        self.button_arrow_up.setStyleSheet("background-color: rgb(255, 0, 0, 0);")
        self.button_arrow_up.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/images/help_image/arrow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_arrow_up.setIcon(icon17)
        self.button_arrow_up.setIconSize(QtCore.QSize(20, 20))
        self.button_arrow_up.setObjectName("button_arrow_up")
        self.button_arrow_down = QtWidgets.QPushButton(self.centralwidget)
        self.button_arrow_down.setGeometry(QtCore.QRect(1670, 243, 41, 31))
        self.button_arrow_down.setStyleSheet("background-color: rgb(255, 0, 0, 0);")
        self.button_arrow_down.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/images/help_image/arrow-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_arrow_down.setIcon(icon18)
        self.button_arrow_down.setIconSize(QtCore.QSize(20, 20))
        self.button_arrow_down.setObjectName("button_arrow_down")
        self.button_start_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_start_pag.setGeometry(QtCore.QRect(1330, 249, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.button_start_pag.setFont(font)
        self.button_start_pag.setStyleSheet("background-color: rgb(255, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));")
        self.button_start_pag.setObjectName("button_start_pag")
        self.button_one_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_one_pag.setGeometry(QtCore.QRect(1360, 249, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.button_one_pag.setFont(font)
        self.button_one_pag.setStyleSheet("background-color: rgb(255, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));")
        self.button_one_pag.setObjectName("button_one_pag")
        self.button_two_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_two_pag.setGeometry(QtCore.QRect(1390, 249, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.button_two_pag.setFont(font)
        self.button_two_pag.setStyleSheet("background-color: rgb(255, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));")
        self.button_two_pag.setObjectName("button_two_pag")
        self.button_three_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_three_pag.setGeometry(QtCore.QRect(1415, 249, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.button_three_pag.setFont(font)
        self.button_three_pag.setStyleSheet("background-color: rgb(255, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));")
        self.button_three_pag.setObjectName("button_three_pag")
        self.button_end_pag = QtWidgets.QPushButton(self.centralwidget)
        self.button_end_pag.setGeometry(QtCore.QRect(1450, 249, 41, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.button_end_pag.setFont(font)
        self.button_end_pag.setStyleSheet("background-color: rgb(255, 0, 0, 0);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));")
        self.button_end_pag.setObjectName("button_end_pag")
        self.label_help_pag_left = QtWidgets.QLabel(self.centralwidget)
        self.label_help_pag_left.setGeometry(QtCore.QRect(1302, 250, 51, 21))
        self.label_help_pag_left.setStyleSheet("image: url(:/images/help_image/help_button_pag.png);")
        self.label_help_pag_left.setText("")
        self.label_help_pag_left.setObjectName("label_help_pag_left")
        self.label_help_pag_right = QtWidgets.QLabel(self.centralwidget)
        self.label_help_pag_right.setGeometry(QtCore.QRect(1471, 250, 51, 21))
        self.label_help_pag_right.setStyleSheet("image: url(:/images/help_image/help_button_pag.png);")
        self.label_help_pag_right.setText("")
        self.label_help_pag_right.setObjectName("label_help_pag_right")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(1170, 250, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab")
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("QPushButton{\n"
"color: rgb(137, 137, 137);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 254, 157, 255), stop:1 rgba(0, 201, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"font: bold;\n"
"}")
        self.button_start.setObjectName("button_start")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pythonист"))
        self.button_overview.setText(_translate("MainWindow", "  Overview"))
        self.button_analytic.setText(_translate("MainWindow", "  Analytics"))
        self.button_product.setText(_translate("MainWindow", "  Products"))
        self.button_order.setText(_translate("MainWindow", "  Orders"))
        self.button_transaction.setText(_translate("MainWindow", "  Transacations"))
        self.button_report.setText(_translate("MainWindow", "  Reports"))
        self.label_menu.setText(_translate("MainWindow", "MENU"))
        self.label_others.setText(_translate("MainWindow", "OTHERS"))
        self.button_setting.setText(_translate("MainWindow", " Settings"))
        self.button_message.setText(_translate("MainWindow", " Messages"))
        self.button_help.setText(_translate("MainWindow", " Help && Support"))
        self.label_background_profile.setText(_translate("MainWindow", "View Profile ->"))
        self.label_name_avatar.setText(_translate("MainWindow", "Alex Grigorev"))
        self.label_name_page.setText(_translate("MainWindow", "Analytics Dashboard"))
        self.textbox_search.setPlaceholderText(_translate("MainWindow", "Search for anything"))
        self.label_currence_header.setText(_translate("MainWindow", "Currency quote"))
        self.label_value_one.setText(_translate("MainWindow", "0$"))
        self.label_value_three.setText(_translate("MainWindow", "30$"))
        self.label_value_two.setText(_translate("MainWindow", "15$"))
        self.label_value_four.setText(_translate("MainWindow", "45$"))
        self.label_value_five.setText(_translate("MainWindow", "60$"))
        self.label_value_six.setText(_translate("MainWindow", "75$"))
        self.label_month.setText(_translate("MainWindow", "Jan"))
        self.label_month_2.setText(_translate("MainWindow", "Feb"))
        self.label_month_3.setText(_translate("MainWindow", "Mar"))
        self.label_month_4.setText(_translate("MainWindow", "Apr"))
        self.label_month_5.setText(_translate("MainWindow", "May"))
        self.label_month_6.setText(_translate("MainWindow", "Jun"))
        self.label_month_7.setText(_translate("MainWindow", "Jul"))
        self.label_month_8.setText(_translate("MainWindow", "Aug"))
        self.label_month_9.setText(_translate("MainWindow", "Sep"))
        self.label_month_10.setText(_translate("MainWindow", "Oct"))
        self.label_month_11.setText(_translate("MainWindow", "Nov"))
        self.label_month_12.setText(_translate("MainWindow", "Dec"))
        self.combobox_early.setCurrentText(_translate("MainWindow", "Yearly"))
        self.combobox_early.setItemText(0, _translate("MainWindow", "Yearly"))
        self.combobox_early.setItemText(1, _translate("MainWindow", "2023"))
        self.combobox_early.setItemText(2, _translate("MainWindow", "2022"))
        self.combobox_early.setItemText(3, _translate("MainWindow", "2021"))
        self.combobox_early.setItemText(4, _translate("MainWindow", "2020"))
        self.combobox_monthly.setCurrentText(_translate("MainWindow", "Monthly"))
        self.combobox_monthly.setItemText(0, _translate("MainWindow", "Monthly"))
        self.combobox_monthly.setItemText(1, _translate("MainWindow", "January"))
        self.combobox_monthly.setItemText(2, _translate("MainWindow", "February"))
        self.combobox_monthly.setItemText(3, _translate("MainWindow", "March"))
        self.combobox_monthly.setItemText(4, _translate("MainWindow", "April"))
        self.combobox_weekly.setCurrentText(_translate("MainWindow", "Weekly"))
        self.combobox_weekly.setItemText(0, _translate("MainWindow", "Weekly"))
        self.combobox_weekly.setItemText(1, _translate("MainWindow", "Monday"))
        self.combobox_weekly.setItemText(2, _translate("MainWindow", "Tuesday"))
        self.combobox_weekly.setItemText(3, _translate("MainWindow", "Wednesday"))
        self.combobox_weekly.setItemText(4, _translate("MainWindow", "Thurday"))
        self.label_percent_value.setText(_translate("MainWindow", "0%"))
        self.label_percent_value_2.setText(_translate("MainWindow", "20%"))
        self.label_percent_value_3.setText(_translate("MainWindow", "40%"))
        self.label_percent_value_4.setText(_translate("MainWindow", "60%"))
        self.label_percent_value_5.setText(_translate("MainWindow", "80%"))
        self.label_percent_value_6.setText(_translate("MainWindow", "100%"))
        self.label_grow_month.setText(_translate("MainWindow", "Jan"))
        self.label_grow_header.setText(_translate("MainWindow", "Growth(%)"))
        self.label_grow_month_2.setText(_translate("MainWindow", "Feb"))
        self.label_grow_month_3.setText(_translate("MainWindow", "Mar"))
        self.label_grow_month_4.setText(_translate("MainWindow", "Apr"))
        self.label_grow_month_5.setText(_translate("MainWindow", "May"))
        self.label_grow_month_6.setText(_translate("MainWindow", "Jun"))
        self.label_grow_month_7.setText(_translate("MainWindow", "Jul"))
        self.label_grow_month_8.setText(_translate("MainWindow", "Aug"))
        self.label_grow_month_9.setText(_translate("MainWindow", "Sep"))
        self.label_grow_month_10.setText(_translate("MainWindow", "Oct"))
        self.label_grow_month_11.setText(_translate("MainWindow", "Nov"))
        self.label_grow_month_12.setText(_translate("MainWindow", "Dec"))
        self.combobox_early_2.setCurrentText(_translate("MainWindow", "Select range"))
        self.combobox_early_2.setItemText(0, _translate("MainWindow", "Select range"))
        self.combobox_early_2.setItemText(1, _translate("MainWindow", "Jan - Dec `23"))
        self.combobox_early_2.setItemText(2, _translate("MainWindow", "Jan - Dec `22"))
        self.combobox_early_2.setItemText(3, _translate("MainWindow", "Jan - Dec `21"))
        self.combobox_early_2.setItemText(4, _translate("MainWindow", "Jan - Dec `20"))
        self.label_best_percent.setText(_translate("MainWindow", "4.8%"))
        self.label_value_is_best.setText(_translate("MainWindow", "15000$"))
        self.label_best_value.setText(_translate("MainWindow", "Best Value"))
        self.label_best_from.setText(_translate("MainWindow", "from yearly"))
        self.label_worst_percent.setText(_translate("MainWindow", "7.3%"))
        self.label_worst_value.setText(_translate("MainWindow", "Worst Value"))
        self.label_worst_from.setText(_translate("MainWindow", "from yearly"))
        self.label_value_is_worst.setText(_translate("MainWindow", "1200$"))
        self.label_average_from.setText(_translate("MainWindow", "from yearly"))
        self.label_value_is_average.setText(_translate("MainWindow", "6000$"))
        self.label_average_percent.setText(_translate("MainWindow", "10.3%"))
        self.label_average_value.setText(_translate("MainWindow", "Average Value"))
        self.label_Requested_data.setText(_translate("MainWindow", "Requested Data"))
        self.label_helper_percent_value.setText(_translate("MainWindow", "76%"))
        self.label_numcode.setText(_translate("MainWindow", "Numcode"))
        self.label_charcode.setText(_translate("MainWindow", "Charcode"))
        self.label_nominal.setText(_translate("MainWindow", "Nominal"))
        self.label_name.setText(_translate("MainWindow", "Name Currency"))
        self.label_value.setText(_translate("MainWindow", "Value"))
        self.label_date.setText(_translate("MainWindow", "Date"))
        self.label_value_numcode_1.setText(_translate("MainWindow", "#036"))
        self.label_value_charcode_1.setText(_translate("MainWindow", "#AUD"))
        self.label_value_nominal_1.setText(_translate("MainWindow", "#1000"))
        self.label_value_date_1.setText(_translate("MainWindow", "02.03.2002"))
        self.label_value_name_1.setText(_translate("MainWindow", "Австралийский доллар"))
        self.label_value_value_1.setText(_translate("MainWindow", "16.0102"))
        self.button_filter_data.setText(_translate("MainWindow", "Filter By"))
        self.label_value_charcode_2.setText(_translate("MainWindow", "#GBP"))
        self.label_value_date_2.setText(_translate("MainWindow", "02.03.2002"))
        self.label_value_nominal_2.setText(_translate("MainWindow", "#1"))
        self.label_value_name_2.setText(_translate("MainWindow", "Фунт стерлинга"))
        self.label_value_numcode_2.setText(_translate("MainWindow", "#826"))
        self.label_value_value_2.setText(_translate("MainWindow", "43,8254"))
        self.label_value_charcode_3.setText(_translate("MainWindow", "#BYR"))
        self.label_value_date_3.setText(_translate("MainWindow", "02.03.2002"))
        self.label_value_nominal_3.setText(_translate("MainWindow", "#1000"))
        self.label_value_name_3.setText(_translate("MainWindow", "Белорусский рубль"))
        self.label_value_numcode_3.setText(_translate("MainWindow", "#974"))
        self.label_value_value_3.setText(_translate("MainWindow", "18,4290"))
        self.label_value_charcode_4.setText(_translate("MainWindow", "#DKK"))
        self.label_value_date_4.setText(_translate("MainWindow", "02.03.2002"))
        self.label_value_nominal_4.setText(_translate("MainWindow", "#10"))
        self.label_value_name_4.setText(_translate("MainWindow", "Датский крон"))
        self.label_value_numcode_4.setText(_translate("MainWindow", "#208"))
        self.label_value_value_4.setText(_translate("MainWindow", "36,1010"))
        self.label_value_charcode_5.setText(_translate("MainWindow", "#USD"))
        self.label_value_date_5.setText(_translate("MainWindow", "02.03.2002"))
        self.label_value_nominal_5.setText(_translate("MainWindow", "#1"))
        self.label_value_name_5.setText(_translate("MainWindow", "Доллар США"))
        self.label_value_numcode_5.setText(_translate("MainWindow", "#840"))
        self.label_value_value_5.setText(_translate("MainWindow", "30,9436"))
        self.combobox_sort_data.setCurrentText(_translate("MainWindow", "Sort By: Date "))
        self.combobox_sort_data.setItemText(0, _translate("MainWindow", "Sort By: Date "))
        self.combobox_sort_data.setItemText(1, _translate("MainWindow", "Sort By: Value"))
        self.combobox_sort_data.setItemText(2, _translate("MainWindow", "Sort By: Name"))
        self.combobox_sort_data.setItemText(3, _translate("MainWindow", "Sort By: Nominal"))
        self.combobox_sort_data.setItemText(4, _translate("MainWindow", "Sort By: Charcode"))
        self.combobox_sort_data.setItemText(5, _translate("MainWindow", "Sort By: Numcode"))
        self.button_start_pag.setText(_translate("MainWindow", "1"))
        self.button_one_pag.setText(_translate("MainWindow", "2"))
        self.button_two_pag.setText(_translate("MainWindow", "3"))
        self.button_three_pag.setText(_translate("MainWindow", "4"))
        self.button_end_pag.setText(_translate("MainWindow", "20"))
        self.button_start.setText(_translate("MainWindow", "Start"))

